hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}-${method}-${ls}-${lr}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metrics.json"
model_name: "ViT-B/16"
prompt_template: "a bad photo of a {}."

batch_size: 64
increment: ${initial_increment}
initial_increment: 2  
scenario: "class"
dataset: "cifar100"

method: "ext"
lr: 1.e-6
ls: 0.2
we: null
avg_freq: 10
ref_dataset: "conceptual_captions"
ref_sentences: "conceptual_captions"

epochs: 1