hydra:
  run:
    dir: ./experiments/${scenario}/${dataset}_${initial_increment}-${increment}-${method}-${ce_method}-${lr}-${ls}-${weight_decay}
  job:
    chdir: true

  job_logging:
    version: 1
    formatters:
      simple:
        format: '%(message)s'

class_order: ""
dataset_root: ""
workdir: ""
log_path: "metrics.json"
model_name: "ViT-B/16"
prompt_template: "a good photo of a {}."

batch_size: 128
initial_increment: 10  
increment: ${initial_increment}
scenario: "class"
dataset: "imagenet100"

method: "finetune"
lr: 7e-6
ls: 0
weight_decay: 0.1
we: 
avg_freq: 
ref_model: 
ref_dataset: 
ref_sentences: "conceptual_captions"
ce_method: "ext"
l2: 0